name: Update JSON File

on:
  push:
    paths:
      - important_stock_codes.json  # 仅当 JSON 文件发生更改时触发

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Commit Updated JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add important_stock_codes.json
          git commit -m "Update JSON file" || echo "No changes to commit"
          git push
